server:
  port: 8071
spring:
  application:
    name: gateway-service-a
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true  # 启用注册中心定位网关服务，启用后可直接使用应用名程调用服务
      routes:
        # 路由标识
        - id: gateway-service-a
          # 目标服务URL
          uri: https://www.baidu.com
          # 断言
          predicates:
            - After=2019-01-01T00:00:00+08:00[Asia/Shanghai]
#            - Before=2049-01-01T00:00:00+08:00[Asia/Shanghai]
#            - Between=2019-01-01T00:00:00+08:00[Asia/Shanghai], 2049-01-01T00:00:00+08:00[Asia/Shanghai]
#            - Cookie=sessionId, test
#            - Header=X-Request-Id, \d+
#            - Host=**.baidu.com
#            - Method=GET
#            - Path=/a
#            - Query=name
#            - RemoteAddr=192.168.1.1/24
#          filter:
#            # 截取Path位数
#            - StripPrefix=1
eureka:
  instance:
    hostname: localhost
    instance-id: ${spring.application.name}:${server.port}
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/